export const COMPANY = {
  name: "Infinite Rankers",
  domain: "infiniterankers.io",
  email: "contact@infiniterankers.io",
  phone: "(703) 415-9373",
  address: "203 N Caroline Pl, Dover, DE 19904, USA",
  tagline: "AI Revenue Growth Agency",
};

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  { label: "Services", href: "/services" },
  { label: "Portfolio", href: "/portfolio" },
  { label: "Pricing", href: "/pricing" },
  { label: "Blog", href: "/blog" },
  { label: "Contact", href: "/contact" },
];

export const SERVICE_CATEGORIES = [
  {
    id: "ai-automation",
    title: "AI & Automation Systems",
    description: "Intelligent automation that works 24/7 to capture, qualify, and convert leads into paying customers.",
    icon: "Bot",
    services: [
      { slug: "ai-calling-agent", title: "AI Calling Agent", shortDesc: "Automated outbound and inbound calls that qualify leads and book appointments around the clock.", icon: "Phone" },
      { slug: "ai-receptionist", title: "AI Receptionist", shortDesc: "Never miss a call again. AI answers, qualifies, and routes every inquiry instantly.", icon: "Headphones" },
      { slug: "ai-lead-qualification", title: "AI Lead Qualification Bot", shortDesc: "Automatically score and qualify leads so your sales team only talks to buyers.", icon: "UserCheck" },
      { slug: "ai-appointment-booking", title: "AI Appointment Booking System", shortDesc: "Let AI fill your calendar with qualified prospects while you focus on closing.", icon: "CalendarCheck" },
      { slug: "ai-follow-up", title: "AI Follow-Up Automation", shortDesc: "Never lose a lead to poor follow-up. AI nurtures every prospect automatically.", icon: "MailCheck" },
      { slug: "ai-sales-assistant", title: "AI Sales Assistant", shortDesc: "AI-powered sales support that helps your team close more deals faster.", icon: "TrendingUp" },
      { slug: "ai-chatbot", title: "AI Chatbot", shortDesc: "Website, WhatsApp, and Messenger chatbot that engages visitors 24/7.", icon: "MessageSquare" },
      { slug: "ai-email-automation", title: "AI Email Automation", shortDesc: "Smart email sequences that adapt to prospect behavior and maximize replies.", icon: "Mail" },
      { slug: "ai-sms-automation", title: "AI SMS Automation", shortDesc: "High-response SMS campaigns powered by AI for instant engagement.", icon: "Smartphone" },
      { slug: "crm-automation", title: "CRM Automation", shortDesc: "Automate your entire CRM workflow from lead entry to deal closure.", icon: "Database" },
      { slug: "workflow-automation", title: "Workflow Automation", shortDesc: "Connect and automate every tool in your sales and marketing stack.", icon: "Workflow" },
    ],
  },
  {
    id: "lead-generation",
    title: "Lead Generation Systems",
    description: "High-performance advertising and SEO systems that drive qualified traffic and revenue.",
    icon: "Target",
    services: [
      { slug: "google-ads", title: "Google Ads Revenue Engine", shortDesc: "Data-driven Google Ads campaigns that maximize ROI and revenue.", icon: "Search" },
      { slug: "meta-ads", title: "Meta Ads Growth Engine", shortDesc: "Facebook and Instagram advertising that generates qualified leads at scale.", icon: "Megaphone" },
      { slug: "seo-authority", title: "SEO Authority Growth System", shortDesc: "Dominate search rankings and build organic traffic that converts.", icon: "BarChart3" },
      { slug: "local-seo", title: "Local SEO & Google Business", shortDesc: "Own your local market with optimized Google Business and local search presence.", icon: "MapPin" },
      { slug: "conversion-funnels", title: "Conversion Funnel Building", shortDesc: "Multi-step funnels designed to turn cold traffic into paying customers.", icon: "Filter" },
      { slug: "landing-page-optimization", title: "Landing Page Optimization", shortDesc: "High-converting landing pages that turn visitors into leads and revenue.", icon: "MousePointer" },
      { slug: "conversion-rate-optimization", title: "Conversion Rate Optimization", shortDesc: "Data-backed testing and optimization to maximize every visitor's value.", icon: "Percent" },
    ],
  },
  {
    id: "social-content",
    title: "Social Media & Content",
    description: "Strategic content and social media presence that builds authority and drives engagement.",
    icon: "Share2",
    services: [
      { slug: "social-media-marketing", title: "Social Media Marketing", shortDesc: "Strategic social presence across platforms to build brand authority.", icon: "Globe" },
      { slug: "instagram-growth", title: "Instagram Growth & Posting", shortDesc: "Consistent, engaging Instagram content that grows your audience organically.", icon: "Camera" },
      { slug: "facebook-growth", title: "Facebook Growth & Posting", shortDesc: "Facebook content strategy that builds community and drives leads.", icon: "ThumbsUp" },
      { slug: "content-writing", title: "Content Writing & Strategy", shortDesc: "Authority-building content that positions you as the industry leader.", icon: "FileText" },
      { slug: "branding-design", title: "Branding & Creative Design", shortDesc: "Premium brand identity that commands trust and recognition.", icon: "Palette" },
      { slug: "video-marketing", title: "Short Form Video Marketing", shortDesc: "Scroll-stopping video content optimized for engagement and reach.", icon: "Video" },
    ],
  },
  {
    id: "development",
    title: "Development & Technology",
    description: "Custom-built technology solutions that power your growth infrastructure.",
    icon: "Code",
    services: [
      { slug: "website-development", title: "Website Development", shortDesc: "High-performance websites designed for conversion and growth.", icon: "Monitor" },
      { slug: "landing-page-development", title: "Landing Page Development", shortDesc: "Fast, responsive landing pages built to convert traffic into leads.", icon: "Layout" },
      { slug: "crm-setup", title: "CRM Setup & Integration", shortDesc: "Professional CRM implementation customized for your sales process.", icon: "Settings" },
      { slug: "saas-integrations", title: "SaaS Integrations", shortDesc: "Seamless integration between your tools for unified data flow.", icon: "Plug" },
      { slug: "marketing-automation-setup", title: "Marketing Automation Setup", shortDesc: "End-to-end marketing automation configured for maximum impact.", icon: "Zap" },
      { slug: "analytics-dashboard", title: "Dashboard & Analytics Setup", shortDesc: "Real-time dashboards and analytics to track every metric that matters.", icon: "PieChart" },
    ],
  },
];

export const ALL_SERVICES = SERVICE_CATEGORIES.flatMap(cat =>
  cat.services.map(s => ({ ...s, category: cat.title, categoryId: cat.id }))
);

export const CASE_STUDIES = [
  {
    id: "1",
    title: "Local Dental Practice Revenue Transformation",
    business: "Premier Dental Care — Multi-location dental practice",
    challenge: "Struggling with inconsistent patient flow and relying on word-of-mouth referrals. Monthly new patient count had plateaued at 15-20.",
    solution: "Deployed AI Calling Agent + Google Ads Revenue Engine + AI Appointment Booking System. Built automated follow-up sequences and optimized Google Business profile.",
    results: { metric1: "340%", label1: "Increase in New Patients", metric2: "$48K", label2: "Monthly Revenue Growth", metric3: "89%", label3: "Appointment Show Rate", metric4: "4.2x", label4: "Return on Ad Spend" },
    tags: ["AI Automation", "Google Ads", "Local SEO"],
    label: "Sample Case Study",
  },
  {
    id: "2",
    title: "E-Commerce Brand Scaling System",
    business: "LuxeHome Essentials — Premium home goods e-commerce",
    challenge: "High cart abandonment rate of 78%, low repeat customer rate, and inefficient ad spend across Meta and Google platforms.",
    solution: "Implemented AI Email Automation + Meta Ads Growth Engine + Conversion Funnel Building. Created personalized retargeting sequences and abandoned cart recovery flows.",
    results: { metric1: "62%", label1: "Cart Recovery Rate", metric2: "5.8x", label2: "ROAS Improvement", metric3: "$220K", label3: "Monthly Revenue Increase", metric4: "45%", label4: "Repeat Purchase Rate" },
    tags: ["Meta Ads", "Email Automation", "CRO"],
    label: "Sample Case Study",
  },
  {
    id: "3",
    title: "Real Estate Agency Lead Generation",
    business: "Skyline Realty Group — Luxury real estate brokerage",
    challenge: "Generating only 30 leads per month with a 5% conversion rate. Sales team spent 60% of time on unqualified prospects.",
    solution: "Built AI Lead Qualification Bot + AI SMS Automation + Landing Page Optimization. Automated lead scoring and instant response system.",
    results: { metric1: "280%", label1: "Lead Volume Increase", metric2: "34%", label2: "Lead-to-Client Rate", metric3: "12min", label3: "Avg Response Time", metric4: "$1.2M", label4: "Revenue in 6 Months" },
    tags: ["AI Qualification", "SMS Automation", "Landing Pages"],
    label: "Sample Case Study",
  },
  {
    id: "4",
    title: "SaaS Company Growth Acceleration",
    business: "CloudSync Pro — B2B SaaS platform",
    challenge: "High churn rate of 8% monthly, lengthy sales cycle of 45 days, and inefficient demo booking process losing 40% of interested prospects.",
    solution: "Deployed AI Sales Assistant + AI Chatbot + Workflow Automation + CRM Automation. Created intelligent demo scheduling and onboarding sequences.",
    results: { metric1: "67%", label1: "Churn Reduction", metric2: "18 days", label2: "Sales Cycle Shortened", metric3: "420%", label3: "Demo Bookings Increase", metric4: "$85K", label4: "MRR Growth" },
    tags: ["AI Chatbot", "CRM Automation", "Sales Assistant"],
    label: "Sample Case Study",
  },
  {
    id: "5",
    title: "Law Firm Client Acquisition System",
    business: "Sterling & Associates — Personal injury law firm",
    challenge: "Inconsistent case intake process, missed calls during off-hours, and no systematic follow-up resulting in lost potential clients.",
    solution: "Implemented AI Receptionist + AI Follow-Up Automation + SEO Authority Growth System. Built 24/7 intake system with automated case qualification.",
    results: { metric1: "190%", label1: "Case Intake Increase", metric2: "24/7", label2: "Response Coverage", metric3: "$320K", label3: "Revenue Per Quarter", metric4: "92%", label4: "Client Satisfaction" },
    tags: ["AI Receptionist", "SEO", "Follow-Up Automation"],
    label: "Sample Case Study",
  },
  {
    id: "6",
    title: "Fitness Studio Membership Growth",
    business: "FitCore Studios — Boutique fitness chain",
    challenge: "Membership growth stagnated at 200 active members. Social media presence was minimal and paid advertising had low ROI.",
    solution: "Built Social Media Marketing + Instagram Growth + Meta Ads Growth Engine + AI Appointment Booking. Created community-driven content strategy with automated trial booking.",
    results: { metric1: "520", label1: "Active Members (from 200)", metric2: "15K", label2: "Instagram Followers Gained", metric3: "78%", label3: "Trial-to-Member Rate", metric4: "3.6x", label4: "Revenue Growth" },
    tags: ["Social Media", "Meta Ads", "AI Booking"],
    label: "Sample Case Study",
  },
  {
    id: "7",
    title: "Restaurant Chain Digital Transformation",
    business: "Harvest Kitchen — Farm-to-table restaurant group",
    challenge: "No online ordering system, poor local visibility, and zero automated marketing. Each location managed marketing independently with inconsistent results.",
    solution: "Deployed Website Development + Local SEO & Google Business + AI SMS Automation + Content Writing & Strategy. Unified marketing across all locations.",
    results: { metric1: "240%", label1: "Online Orders Increase", metric2: "#1", label2: "Local Search Rankings", metric3: "4,200", label3: "Monthly SMS Subscribers", metric4: "$180K", label4: "Annual Revenue Uplift" },
    tags: ["Local SEO", "Web Development", "SMS Automation"],
    label: "Sample Case Study",
  },
];

export const PRICING_TIERS = [
  {
    name: "Starter System",
    price: "$1,497",
    period: "/month",
    description: "Perfect for small businesses ready to automate their first revenue systems.",
    features: [
      "AI Chatbot (Website)",
      "Basic CRM Setup",
      "Email Automation (up to 1,000 contacts)",
      "1 Landing Page",
      "Monthly Performance Report",
      "Google Business Optimization",
      "Basic SEO Audit",
      "Email Support",
    ],
    cta: "Get Started",
    popular: false,
  },
  {
    name: "Growth System",
    price: "$3,497",
    period: "/month",
    description: "For growing businesses that need a complete AI-powered revenue engine.",
    features: [
      "Everything in Starter, plus:",
      "AI Calling Agent",
      "AI Lead Qualification Bot",
      "AI Appointment Booking",
      "Google Ads Management",
      "Meta Ads Management",
      "Full CRM Automation",
      "3 Landing Pages",
      "Social Media Management (2 platforms)",
      "Weekly Strategy Calls",
      "Priority Support",
    ],
    cta: "Scale Now",
    popular: true,
  },
  {
    name: "Scale System",
    price: "$6,997",
    period: "/month",
    description: "Enterprise-grade AI automation for businesses ready to dominate their market.",
    features: [
      "Everything in Growth, plus:",
      "AI Receptionist (24/7)",
      "AI Sales Assistant",
      "Full Workflow Automation",
      "Advanced Analytics Dashboard",
      "SEO Authority System",
      "Content Writing & Strategy",
      "Video Marketing",
      "Unlimited Landing Pages",
      "Social Media (All Platforms)",
      "Dedicated Account Manager",
      "Daily Reporting",
    ],
    cta: "Dominate Your Market",
    popular: false,
  },
];

export const TESTIMONIALS = [
  {
    name: "Michael Chen",
    role: "CEO, Premier Dental Care",
    text: "Infinite Rankers transformed our patient acquisition. The AI calling agent alone books 40+ appointments per week without any human involvement. Our revenue has more than tripled.",
    rating: 5,
  },
  {
    name: "Sarah Williams",
    role: "Founder, LuxeHome Essentials",
    text: "The AI email automation and retargeting system they built recovered over $220K in abandoned carts in just 3 months. The ROI is incredible.",
    rating: 5,
  },
  {
    name: "David Rodriguez",
    role: "Managing Partner, Sterling & Associates",
    text: "We never miss a potential client call now. The AI receptionist handles intake 24/7 and the follow-up automation has increased our case conversion by 190%.",
    rating: 5,
  },
  {
    name: "Jennifer Park",
    role: "Owner, FitCore Studios",
    text: "From 200 to 520 active members in 6 months. The combination of social media marketing and AI booking automation changed everything for our studios.",
    rating: 5,
  },
  {
    name: "Robert Thompson",
    role: "VP Sales, CloudSync Pro",
    text: "Our sales cycle went from 45 days to 18 days. The AI sales assistant and automated demo booking system have completely revolutionized our pipeline.",
    rating: 5,
  },
];

export const BLOG_POSTS = [
  {
    id: "1",
    slug: "ai-automation-revenue-growth-2025",
    title: "How AI Automation Is Driving 10x Revenue Growth in 2025",
    excerpt: "Discover how forward-thinking businesses are leveraging AI automation systems to generate customers and revenue on autopilot.",
    category: "AI Automation",
    readTime: "8 min read",
    date: "Jan 28, 2025",
  },
  {
    id: "2",
    slug: "google-ads-roi-local-business",
    title: "Google Ads for Local Businesses: A Data-Driven ROI Framework",
    excerpt: "Learn the exact framework we use to generate 4-6x ROAS for local businesses using AI-optimized Google Ads campaigns.",
    category: "Lead Generation",
    readTime: "12 min read",
    date: "Jan 15, 2025",
  },
  {
    id: "3",
    slug: "ai-chatbot-lead-conversion",
    title: "AI Chatbots: Converting 78% More Website Visitors Into Leads",
    excerpt: "How intelligent chatbots are revolutionizing lead capture and qualification for businesses across every industry.",
    category: "AI Automation",
    readTime: "6 min read",
    date: "Jan 5, 2025",
  },
  {
    id: "4",
    slug: "crm-automation-sales-pipeline",
    title: "The Ultimate CRM Automation Playbook for Sales Teams",
    excerpt: "Stop losing deals to manual processes. Here's how to automate your entire sales pipeline from lead to close.",
    category: "Sales Automation",
    readTime: "10 min read",
    date: "Dec 20, 2024",
  },
  {
    id: "5",
    slug: "seo-vs-paid-ads-strategy",
    title: "SEO vs Paid Ads: Building a Unified Revenue Strategy",
    excerpt: "Why the best growth strategies combine organic search dominance with paid advertising for maximum market capture.",
    category: "Strategy",
    readTime: "9 min read",
    date: "Dec 10, 2024",
  },
  {
    id: "6",
    slug: "ai-follow-up-sequences",
    title: "AI Follow-Up Sequences That Close 3x More Deals",
    excerpt: "The science behind AI-powered follow-up automation and how it's helping sales teams dramatically increase close rates.",
    category: "AI Automation",
    readTime: "7 min read",
    date: "Dec 1, 2024",
  },
];

export const HOW_IT_WORKS_STEPS = [
  { step: 1, title: "Traffic Generation", description: "We drive qualified traffic through AI-optimized ads, SEO, and content strategies.", icon: "Globe" },
  { step: 2, title: "AI Qualification", description: "Our AI systems instantly engage, qualify, and score every lead automatically.", icon: "Bot" },
  { step: 3, title: "Smart Routing", description: "Qualified leads are routed to your CRM with full context and priority scoring.", icon: "ArrowRight" },
  { step: 4, title: "Automated Booking", description: "AI books appointments directly into your calendar — no manual scheduling.", icon: "CalendarCheck" },
  { step: 5, title: "Revenue Growth", description: "Close more deals with AI-assisted sales and automated follow-up sequences.", icon: "DollarSign" },
];

export const ACHIEVEMENTS = [
  { value: "500+", label: "Businesses Transformed" },
  { value: "$120M+", label: "Revenue Generated" },
  { value: "2.4M+", label: "Leads Qualified by AI" },
  { value: "98%", label: "Client Retention Rate" },
];
