const fs = require("fs");

function addPages(pages) {
  let lp = fs.readFileSync("client/src/lib/landing-pages.ts","utf8");
  const lpIdx = lp.lastIndexOf("\n];\n\nexport const ALL_LANDING_PAGES");
  if(lpIdx===-1){console.error("LP insert not found");process.exit(1);}
  lp = lp.slice(0,lpIdx) + ",\n" + pages.map(p=>JSON.stringify(p,null,2)).join(",\n") + lp.slice(lpIdx);
  fs.writeFileSync("client/src/lib/landing-pages.ts",lp,"utf8");
  let sm = fs.readFileSync("server/sitemap.ts","utf8");
  const smIdx = sm.lastIndexOf('\n];');
  sm = sm.slice(0,smIdx) + ",\n" + pages.map(p=>`  "${p.slug}"`).join(",\n") + sm.slice(smIdx);
  fs.writeFileSync("server/sitemap.ts",sm,"utf8");
  let seo = fs.readFileSync("server/seo.ts","utf8");
  const seoIdx = seo.indexOf('\n};\n\nconst PARTNER');
  if(seoIdx===-1){console.error("SEO insert not found");process.exit(1);}
  const entries = "\n" + pages.map(p=>{
    const faqs=(p.faqs||[]).slice(0,3).map(f=>`{ q: ${JSON.stringify(f.q)}, a: ${JSON.stringify(f.a)} }`).join(", ");
    return `  ${JSON.stringify(p.slug)}: { title: ${JSON.stringify(p.seoTitle)}, desc: ${JSON.stringify(p.seoDescription)}, faqs: [${faqs}] },`;
  }).join("\n");
  seo = seo.slice(0,seoIdx) + entries + seo.slice(seoIdx);
  fs.writeFileSync("server/seo.ts",seo,"utf8");
  console.log(`Added ${pages.length} pages`);
}

const BASE="https://infiniterankers.io";
const CL=[{label:"SEO Services",url:"https://infiniterankers.com/seo-services/"},{label:"Google Ads",url:"https://infiniterankers.com/google-ads-campaign-ppc-campaign/"},{label:"Contact Us",url:"https://infiniterankers.com/contact-us/"}];
const RS=["ai-receptionist","crm-automation","ai-sms-automation"];

function p(slug,type,seoTitle,seoDescription,seoKeywords,badge,heroTitle,heroHighlight,heroSub,stats,ppTitle,ppSub,points,aiTitle,aiSub,aiDesc,caps,plSteps,resTitle,cases,ftItems,ecoDesc,ioF,comF,tms,faqs,ctaTitle,ctaSub,ctaBtn,related){
  return {
    slug,type,seoTitle,seoDescription,seoKeywords,
    canonical:`${BASE}/${slug}`,
    hero:{badge,title:heroTitle,titleHighlight:heroHighlight,subtitle:heroSub,stats},
    painPoints:{title:ppTitle,subtitle:ppSub,points},
    aiSystem:{title:aiTitle,subtitle:aiSub,description:aiDesc,capabilities:caps},
    pipeline:{title:"How It Works — 4 Steps to Results",subtitle:"Simple setup, powerful automation",steps:plSteps},
    results:{title:resTitle,subtitle:"Real results from businesses using our system",cases},
    features:{title:"Complete Feature Set",subtitle:"Everything you need in one platform",items:ftItems},
    ecosystem:{title:"The Complete Ecosystem",subtitle:"AI Revenue Systems + Marketing Authority",description:ecoDesc,
      ioFeatures:ioF,comFeatures:comF,
      comLinks:CL},
    testimonials:tms,faqs,
    cta:{title:ctaTitle,subtitle:ctaSub,buttonText:ctaBtn},
    relatedLandingPages:related||[],relatedServices:RS,comLinks:CL
  };
}

const pt=(t,d,i)=>({title:t,description:d,icon:i});
const st=(s,t,d,i)=>({step:s,title:t,description:d,icon:i});
const cs=(b,ind,m,q)=>({business:b,industry:ind,metrics:m,quote:q});
const m=(v,l)=>({value:v,label:l});
const tm=(n,r,c,q)=>({name:n,role:r,company:c,quote:q,rating:5});
const fq=(q,a)=>({q,a});
const fi=(t,d,i)=>({title:t,description:d,icon:i});
const cap=(t,d,i)=>({title:t,description:d,icon:i});

const pages = [
// SMS/TEXTING CATEGORY
p("business-texting-software","service",
  "Business Texting Software | AI Two-Way SMS for Local Business | Infinite Rankers",
  "AI-powered business texting software that handles two-way SMS conversations, automates follow-ups, and books appointments via text. No annual contract. Free demo.",
  "business texting software, business sms software, two way texting for business, business text messaging",
  "98% SMS Open Rate","Business Texting Software","That Books Appointments",
  "AI-powered business texting that goes beyond mass blasts — two-way AI conversations that qualify leads, answer questions, and book appointments automatically via SMS.",
  [m("98%","SMS Open Rate"),m("58%","Response Rate"),m("3x","More Booked Appointments"),m("24/7","AI Text Coverage")],
  "Why Generic Business Texting Software Falls Short","The limits of SMS blasting tools",
  [pt("Mass Blasts Without Conversation","Texting software that only sends bulk messages misses the revenue in two-way conversations — where leads qualify themselves and appointments get booked.","MessageSquare"),
   pt("No AI to Handle Replies","When customers reply to your texts, someone has to respond. Most texting software has no AI to handle those replies — creating gaps that lose leads to faster competitors.","Cpu"),
   pt("No CRM Connection","Business texting disconnected from your CRM means lost context. Customer conversations don't update deal stages or trigger follow-ups — creating fragmented customer records.","Database"),
   pt("Compliance Complexity","TCPA compliance, opt-out management, and consent tracking require careful handling. Most basic texting tools leave businesses exposed to compliance risk.","Shield")],
  "AI Business Texting That Handles Full Conversations","Not just blasts — intelligent two-way SMS",
  "Our AI business texting system handles complete two-way SMS conversations — answering questions, qualifying leads, handling objections, and booking appointments automatically. Every conversation is logged in your CRM with full context for seamless follow-up.",
  [cap("Two-Way AI Conversations","AI handles complete SMS conversations — not just sends blasts — qualifying leads and booking appointments automatically.","Cpu"),
   cap("CRM Auto-Sync","Every conversation automatically logged to your CRM with full context, lead scoring, and next-step triggers.","Database"),
   cap("Appointment Booking via Text","AI books appointments directly into your calendar through SMS conversation — zero human intervention required.","Calendar"),
   cap("TCPA Compliance Built-In","Automatic opt-in/opt-out management, consent tracking, and compliant messaging flows built into every campaign.","Shield")],
  [st("1","New Lead Texts In","Customer texts your business number — AI responds within 30 seconds, identifies their need, and begins qualification.","MessageSquare"),
   st("2","AI Qualifies via SMS","AI asks qualification questions naturally via text — capturing job type, timeline, budget range, and contact details automatically.","Cpu"),
   st("3","Appointment Booked","Qualified lead is offered available times from your calendar and books directly via SMS — no phone call required.","Calendar"),
   st("4","CRM Updated","Full conversation logged to CRM with qualification score, appointment details, and automated follow-up sequence triggered.","Database")],
  "Business Texting Results Across Industries",
  [cs("Apex Roofing","Roofing",[m("312%","More Estimates Booked"),m("58%","SMS Response Rate"),m("4.8★","Google Rating")],"Our AI texts back every lead within 30 seconds. We book estimate appointments via SMS while I'm on a job site. The system closed 40% more jobs in the first month just from faster response time."),
   cs("Precision Dental","Dental",[m("67%","More Appointments"),m("89%","Show Rate"),m("4.9★","Rating")],"Patients text to ask about our services, AI answers and offers to book an appointment. We went from 20 to 45+ new patient bookings per month just from AI handling text inquiries."),
   cs("Quick Lube Center","Auto Service",[m("178%","More Service Bookings"),m("44%","Lower Response Time"),m("91%","Customer Satisfaction")],"The AI handles every text inquiry even when we're slammed with cars. Customers love getting instant replies. Our booking rate from online inquiries doubled in 60 days.")],
  [fi("Two-Way AI SMS","Full conversational AI via text — not just mass blasts — for genuine lead qualification dialogues.","MessageSquare"),
   fi("Appointment Booking via Text","Leads book directly into your calendar through AI SMS conversation — zero human intervention.","Calendar"),
   fi("CRM Integration","Every SMS conversation synced to your CRM with context, scoring, and follow-up triggers.","Database"),
   fi("TCPA Compliance","Built-in opt-in/opt-out management and consent tracking for full regulatory compliance.","Shield"),
   fi("Review Request via Text","Post-service review requests via SMS achieve 58% response rates vs. 12% for email.","Star"),
   fi("Broadcast Campaigns","Smart SMS campaigns to your customer list for promotions, seasonal offers, and reactivation.","Send")],
  "Business texting is the highest-engagement channel available — 98% open rates, 90-second average read time, and 58% response rates. Combined with AI that handles conversations, appointment booking, and CRM sync, SMS becomes your highest-ROI lead capture and conversion channel.",
  [{title:"AI Revenue System",description:"Complete lead capture, SMS qualification, booking, and CRM automation in one integrated platform."},{title:"No Contract Billing",description:"Month-to-month SMS automation with transparent pricing and no annual commitment."},{title:"Revenue Attribution",description:"Track every appointment booked via SMS back to the exact message and campaign that generated it."}],
  [{title:"SEO",description:"Organic traffic combined with SMS conversion creates the lowest cost-per-acquisition funnel."},{title:"Paid Ads",description:"Drive paid traffic directly into SMS-first funnels for maximum conversion rates."},{title:"Web Design",description:"SMS capture forms and chat-to-text integrations built into your website for seamless lead flow."}],
  [tm("Dan Pierce","Owner","Pierce Plumbing & Drain","The AI texts back faster than any human could. We've booked 80+ appointments via text in the first 2 months. Customers love not having to call — and we love that the AI handles everything while we work."),
   tm("Dr. Susan Lee","Practice Manager","Lee Family Dental","Two-way AI texting changed how we interact with new patients. They text, AI qualifies, appointment is booked. Our team doesn't touch it until the patient shows up. Incredible efficiency."),
   tm("Mike Avery","GM","Avery Auto Care","SMS reply rates are 10x better than email. Our AI handles every reply with a conversation that qualifies and books. We book 30 more service appointments per month without any additional staff.")],
  [fq("Can the AI really handle full SMS conversations?","Yes. Our AI uses advanced natural language processing to handle multi-turn SMS conversations — answering questions, addressing objections, and booking appointments through natural text exchanges that customers rarely distinguish from a human."),
   fq("Is business texting TCPA compliant?","Yes. Our system includes built-in TCPA compliance features — opt-in capture, opt-out management, consent timestamp recording, and compliant messaging flows. We recommend all businesses consult with their attorney for specific compliance questions."),
   fq("What CRMs does the SMS system integrate with?","HubSpot, Salesforce, GoHighLevel, Pipedrive, Zoho, Close.com, and most other major CRM platforms. Bi-directional sync ensures SMS conversations update deal stages, contact records, and trigger follow-up automations automatically."),
   fq("How many texts can I send per month?","Plans are sized based on your business volume. We don't apply artificial caps — packages are structured around your actual customer base and campaign needs with transparent per-message pricing above plan thresholds."),
   fq("What response time does the AI achieve?","The AI responds to inbound SMS within 30 seconds on average — significantly faster than any human team could match, especially outside business hours.")],
  "Get AI Business Texting That Books Appointments Automatically","Free 30-minute demo — see two-way AI SMS in action and test your first automated conversation before committing.","Book My Free SMS Demo",
  ["ai-answering-service","missed-call-text-back","automated-customer-texting","ai-for-small-business"]),

p("text-message-marketing-for-small-business","service",
  "Text Message Marketing for Small Business | AI SMS Campaigns | Infinite Rankers",
  "Text message marketing for small businesses — AI-powered SMS campaigns that get 98% open rates and drive real revenue. No annual contract. Free campaign demo.",
  "text message marketing small business, sms marketing small business, text marketing for local business, small business text campaigns",
  "98% Open Rate Marketing","Text Message Marketing","for Small Business",
  "Small businesses using text message marketing see 98% open rates and 45% response rates — making SMS the highest-engagement marketing channel available. Our AI system manages campaigns, responses, and bookings automatically.",
  [m("98%","SMS Open Rate"),m("45%","Response Rate"),m("$0.01","Cost Per Message"),m("No",  "Annual Contract")],
  "Why Small Businesses Need SMS Marketing","The channel your competitors are ignoring",
  [pt("Email Marketing Is Getting Harder","Email open rates have dropped to 20-25% for most industries. SMS consistently delivers 98% open rates — making it the most reliable channel to reach your customer list.","Mail"),
   pt("Social Media Reach Is Declining","Organic social media reach is below 5% for most business pages. SMS delivers directly to your customer's phone — no algorithm limiting your reach.","TrendingDown"),
   pt("Phone Calls Get Ignored","78% of calls from unknown numbers go to voicemail. Texts from businesses get read. SMS is the communication channel your customers actually prefer.","Phone"),
   pt("Managing Campaigns Is Time-Consuming","Most small business owners don't have time to manually manage SMS campaigns, track responses, and follow up with interested customers. AI automation solves this completely.","Clock")],
  "AI Text Message Marketing for Small Business","Campaigns that run themselves, conversations that convert",
  "Infinite Rankers builds AI-powered SMS marketing systems for small businesses — automating campaign creation, delivery, response handling, and follow-up sequences that convert replies into booked appointments and closed sales.",
  [cap("AI Campaign Builder","Smart campaign templates for promotions, seasonal offers, reactivation, and announcements — personalized for your specific business.","FileText"),
   cap("Two-Way Response AI","When customers reply to campaigns, AI handles the conversation — answering questions and booking appointments automatically.","MessageSquare"),
   cap("Customer List Segmentation","Segment your customer list by service history, last visit date, and purchase behavior for targeted, relevant campaigns.","Users"),
   cap("Campaign Performance Tracking","Real-time tracking of open rates, response rates, appointment bookings, and revenue generated from every campaign.","BarChart3")],
  [st("1","Campaign Built","We build your SMS campaign — promotional offer, reactivation, or announcement — with AI-personalized messaging for your customer segments.","FileText"),
   st("2","Campaign Delivered","SMS campaign goes out to your customer list. Open rates average 98% — typically read within 90 seconds of delivery.","Send"),
   st("3","Replies Handled by AI","Customers who reply are greeted by AI that answers questions, handles the offer, and books appointments — without your team lifting a finger.","Cpu"),
   st("4","Revenue Tracked","Every appointment booked and sale closed from the campaign is tracked — showing exact revenue generated vs. campaign cost.","DollarSign")],
  "Text Message Marketing Results for Small Businesses",
  [cs("Bella's Hair Salon","Personal Services",[m("$4,200","Revenue From 1 Campaign"),m("67%","Appointment Fill Rate"),m("89%","Open Rate")],"Our reactivation SMS campaign reached 340 clients who hadn't visited in 6 months. 67% booked an appointment. We generated $4,200 in appointments from one 3-cent-per-text campaign. SMS ROI is unreal."),
   cs("Quick Clean Carpets","Home Services",[m("312%","More Bookings From SMS"),m("$0.03","Cost Per Message"),m("4.8★","Customer Rating")],"We run seasonal SMS campaigns — spring cleaning, fall carpets — and generate 30+ bookings per campaign automatically. AI handles all replies. I spend 20 minutes setting up a campaign that makes $3,000+."),
   cs("Summit Chiropractic","Chiropractic",[m("178%","More Appointments"),m("$5,800","Monthly SMS Revenue"),m("91%","Patient Satisfaction")],"We reactivate patients who haven't been in 60+ days via SMS. AI texts them, answers questions about their condition, and books appointments. We've reactivated 80+ patients this way — all automated.")],
  [fi("Promotional Campaigns","Seasonal offers, new service announcements, and flash sales delivered directly to your customer list.","Send"),
   fi("Reactivation Campaigns","Automated campaigns reaching customers who haven't visited recently — turning lapsed relationships into bookings.","TrendingUp"),
   fi("AI Reply Management","Two-way AI handles every campaign reply — answering questions and booking appointments automatically.","Cpu"),
   fi("Audience Segmentation","Target specific customer segments by service history, visit frequency, and purchase behavior.","Users"),
   fi("Revenue Attribution","Track exact revenue generated from every SMS campaign — proving ROI with actual dollars, not vanity metrics.","DollarSign"),
   fi("TCPA Compliance","Built-in consent management, opt-out processing, and compliant messaging for regulatory peace of mind.","Shield")],
  "For small businesses, SMS marketing delivers the highest ROI of any marketing channel — at fractions of a penny per message, with 98% open rates and AI that converts replies into booked appointments automatically. No other channel combines reach, engagement, and conversion at this cost.",
  [{title:"SMS + AI System",description:"Complete SMS marketing with AI conversation management — not just blast tools."},{title:"No Contract",description:"Month-to-month SMS marketing with transparent per-message pricing."},{title:"Complete Attribution",description:"Revenue generated from every campaign tracked to the exact message."}],
  [{title:"Local SEO",description:"Organic traffic combined with SMS follow-up for complete local customer acquisition."},{title:"Google Ads",description:"Paid traffic funneled into SMS opt-in flows for maximum conversion."},{title:"Email Marketing",description:"Combined SMS + email campaigns for maximum reach across all customer preferences."}],
  [tm("Rosa Martinez","Owner","Rosa's Tacos & Cantina","Our Thursday lunch SMS 'Come in today, get free guac' campaigns fill the restaurant every week. Open rate is always 95%+. AI handles all replies for catering inquiries. SMS is our most profitable marketing channel."),
   tm("Jake Wilson","Owner","Wilson Lawn Care","Spring campaign SMS reaches all our customers with an early-bird discount for lawn season. We book 6 weeks of work in 3 days from one campaign. At 3 cents per text, the ROI is impossible to beat."),
   tm("Amy Chen","Owner","Chen Pet Grooming","Reactivation campaigns bring back customers who haven't booked in 60+ days. AI replies for them, answers scheduling questions, and books appointments. We recovered $2,800 in revenue from our first reactivation campaign.")],
  [fq("Is text message marketing legal for small businesses?","Yes, with proper consent management. TCPA requires prior consent from customers before texting them for marketing. Our system includes opt-in collection, consent timestamping, and opt-out management to maintain compliance."),
   fq("How do I build my SMS marketing list?","We help you collect opt-ins through your website, at point of sale, on your invoices, and via keyword campaigns. Most businesses collect 50-200 new opt-ins per month depending on customer volume."),
   fq("What kinds of SMS campaigns work best for small business?","Reactivation campaigns (reaching lapsed customers) typically generate the highest ROI. Seasonal promotions, appointment reminders, and flash sales are also highly effective. We build campaign templates specific to your business type."),
   fq("How much does text message marketing cost?","SMS campaigns cost fractions of a penny per message for delivery — typically $0.01-$0.03 per message. Platform fees depend on your customer list size and campaign volume. Most small businesses spend $100-$300/month for significant campaign volume."),
   fq("Will customers find SMS marketing annoying?","Only if you overdo it or send irrelevant content. Businesses that send 1-2 relevant campaigns per month with genuine value see very low opt-out rates (typically under 2%). The key is sending something customers actually want.")],
  "Launch Your First SMS Marketing Campaign — Free","Free SMS campaign setup — we'll build your first campaign, including audience segmentation and AI reply handling, completely free. See your first results before committing.","Launch My Free SMS Campaign",
  ["business-texting-software","automated-customer-texting","sms-customer-follow-up","missed-call-text-back"]),

p("two-way-text-messaging-for-business","service",
  "Two-Way Text Messaging for Business | AI SMS Conversations | Infinite Rankers",
  "Two-way text messaging for business powered by AI — handle customer conversations, qualify leads, and book appointments via SMS automatically. Free demo.",
  "two way text messaging for business, two way texting business, two way sms business, business text conversation",
  "AI-Powered Two-Way SMS","Two-Way Text Messaging","for Business",
  "True two-way SMS conversations powered by AI — not just blasts. Our system handles every inbound text, qualifies leads, answers questions, and books appointments automatically via SMS conversations.",
  [m("98%","SMS Open Rate"),m("30 sec","AI Response Time"),m("58%","Appointment Conversion Rate"),m("24/7","SMS Coverage")],
  "Why One-Way SMS Blasting Isn't Enough","The missed revenue in your reply inbox",
  [pt("Customers Want to Text Back","When you send promotional texts, 30-40% of recipients want to reply with questions. If no one answers quickly, those leads are lost. AI handles every reply instantly.","MessageSquare"),
   pt("Inbound Text Leads Get Lost","Customers who text your business number to inquire about services deserve immediate responses. Most businesses miss these inbound texts entirely or respond hours later.","Inbox"),
   pt("Follow-Up Requires Human Time","After initial outreach, following up with interested prospects via text requires staff time you don't have. AI handles multi-touch follow-up sequences automatically.","Clock"),
   pt("No Qualification System","A human replying to text inquiries without a qualification system is just a chat tool. AI qualifies by intent, budget, timeline, and service type — automatically.","Target")],
  "AI Two-Way Text Messaging for Business","Full conversational SMS at scale",
  "Infinite Rankers' two-way SMS system uses conversational AI to handle every inbound text, qualify prospects, answer common questions, and book appointments — while logging every conversation to your CRM with full context.",
  [cap("Inbound Text Coverage","Every inbound text to your business number is answered by AI within 30 seconds — 24/7, including nights and weekends.","Phone"),
   cap("Natural SMS Conversations","AI maintains context across multi-turn conversations — remembering what was said and building on it naturally.","MessageSquare"),
   cap("Lead Qualification via Text","AI asks qualifying questions conversationally — capturing job type, timeline, budget, and contact details without feeling like a form.","Target"),
   cap("Direct Calendar Booking","Qualified leads are offered appointment times and booked directly into your calendar through SMS — zero friction.","Calendar")],
  [st("1","Customer Texts In","New or existing customer texts your business number. AI responds within 30 seconds with a personalized greeting.","MessageSquare"),
   st("2","AI Qualifies","Through natural conversation, AI qualifies the lead — identifying service need, urgency, and fit.","Target"),
   st("3","Appointment Offered","AI offers available times from your calendar and confirms the booking directly via text.","Calendar"),
   st("4","CRM Updated","Full conversation logged to CRM with lead score, service details, and appointment confirmation.","Database")],
  "Two-Way SMS Results Across Industries",
  [cs("City Wide HVAC","HVAC",[m("267%","More Appointments via SMS"),m("30 sec","Avg. AI Response Time"),m("24/7","Coverage Achieved")],"We used to miss 40% of after-hours service requests. AI now handles every text 24/7 — qualifying the job, capturing the address, and offering available appointment times. We book 30+ more service calls per month from texts alone."),
   cs("Summit Law Group","Legal",[m("189%","More Initial Consultations"),m("4.8★","Client Rating"),m("$0","Missed Inquiry Cost")],"Potential clients text us at all hours with legal questions. AI answers appropriately, qualifies the case type, and schedules consultations. We've added 15 new case consultations per month from AI-handled texts."),
   cs("Metro Pet Hospital","Veterinary",[m("212%","More Appointment Requests"),m("91%","Show Rate"),m("4.9★","Client Rating")],"Pet owners text in a panic when their pet is sick. AI responds calmly, triages urgency, and offers the next available appointment. Our after-hours text response used to be nothing. Now it's 100% AI coverage.")],
  [fi("24/7 Inbound Text Coverage","Every inbound text answered by AI within 30 seconds — never miss a lead, even at midnight.","Clock"),
   fi("Contextual AI Conversations","AI maintains conversation context across multiple exchanges for natural, coherent SMS interactions.","MessageSquare"),
   fi("Qualification Dialogues","AI extracts lead qualification data through natural SMS conversation — not forms.","Target"),
   fi("Calendar Integration","AI books appointments directly into your scheduling system through the SMS conversation.","Calendar"),
   fi("CRM Auto-Logging","Every conversation synced to CRM with full context, lead score, and appointment details.","Database"),
   fi("Outbound Follow-Up","AI initiates follow-up texts with prospects who expressed interest but haven't booked yet.","Send")],
  "Two-way SMS powered by AI creates a scalable customer communication system that would require a full-time staff member to manage manually. At a fraction of that cost, our AI handles hundreds of simultaneous conversations 24/7 — qualifying every lead and booking every appointment.",
  [{title:"Full AI Revenue System",description:"Two-way SMS is one component of a complete lead capture, qualification, and booking system."},{title:"CRM Pipeline Integration",description:"Every SMS conversation feeds directly into your CRM pipeline for seamless lead management."},{title:"No Contract",description:"Month-to-month pricing for two-way SMS — scale up or down based on your business needs."}],
  [{title:"Local SEO",description:"Organic traffic combined with two-way SMS follow-up creates a complete acquisition funnel."},{title:"Paid Ads",description:"Drive paid traffic into SMS-first lead capture flows for maximum conversion."},{title:"Web Design",description:"SMS call-to-action elements integrated throughout your website for continuous lead capture."}],
  [tm("Robert Hall","Owner","Hall Electrical","The two-way AI texting covers us completely. Customers text to schedule service — AI books them. Customers text to check job status — AI updates them. Customers text for pricing — AI educates and qualifies. One system, every scenario."),
   tm("Dr. Jessica Wong","Dentist","Wong Family Dental","Patients text us all the time now — it's their preferred channel. AI handles every text with the same professionalism as our front desk, but available 24/7. New patient inquiries via text increased 140% in 3 months."),
   tm("Frank Garcia","Owner","Garcia Landscaping","I used to miss 5-6 estimate requests per week from texts I didn't see until the next day. AI answers every text within 30 seconds. I haven't missed a single estimate request since launch.")],
  [fq("Can the AI really maintain conversation context across multiple texts?","Yes. Our AI tracks conversation history and maintains full context across multi-turn exchanges — so if a customer asks 'how much does it cost?' then follows with 'what about the premium package?', the AI understands the connection and responds coherently."),
   fq("What happens if a text is too complex for the AI to handle?","For complex scenarios outside the AI's configured scope, the system escalates to a human team member with full conversation context — ensuring no lead is lost due to complexity."),
   fq("How does the AI know what appointment times to offer?","The AI integrates with your calendar (Google Calendar, Calendly, Acuity, or your CRM's scheduling module) in real-time — only offering times that are actually available for the appropriate service type."),
   fq("Does two-way SMS work for B2B businesses?","Yes. B2B two-way SMS works particularly well for appointment scheduling, quote follow-up, and event reminders. We configure AI scripts for B2B contexts including longer sales cycles and multi-stakeholder buying processes."),
   fq("What's the typical setup time?","Most clients are live with full two-way AI SMS within 5-7 business days including calendar integration, CRM sync, AI script configuration, and test conversation approval.")],
  "See Two-Way AI SMS in Action","Free 30-minute demo — watch a live AI SMS conversation qualify a lead and book an appointment in real-time, then see how it would work for your specific business.","Book My Free Two-Way SMS Demo",
  ["business-texting-software","automated-customer-texting","missed-call-text-back","sms-customer-follow-up"]),

p("automated-text-messages-for-business","service",
  "Automated Text Messages for Business | AI SMS Automation | Infinite Rankers",
  "Automated text messages for business — AI-powered SMS sequences for follow-up, reminders, review requests, and lead nurturing. Set it up once and watch it work. Free demo.",
  "automated text messages for business, automated sms for business, business text automation, automated text messaging",
  "Set It Once, Text Customers Forever","Automated Text Messages","for Business",
  "Automated text message sequences for follow-up, appointment reminders, review requests, and lead nurturing — powered by AI that personalizes every message based on your customer data.",
  [m("98%","SMS Open Rate"),m("40-67%","Response Rate"),m("Zero","Manual Texting Required"),m("14",  "Day Setup")],
  "Why Manual Business Texting Doesn't Scale","The problem with inconsistent, manual SMS outreach",
  [pt("Inconsistent Follow-Up Loses Leads","Studies show 80% of sales require 5+ follow-ups, but 44% of salespeople give up after 1. Automated text sequences ensure consistent follow-up without depending on human memory.","TrendingDown"),
   pt("Appointment No-Shows Cost Revenue","Every no-show is lost revenue. Manual reminder texts are often forgotten or sent too late. Automated multi-touch reminders reduce no-shows by 40-60%.","Calendar"),
   pt("Review Requests Get Forgotten","Review generation requires consistent timing — usually within 30 minutes of service completion. Manual review request texting has too many gaps and wrong timing.","Star"),
   pt("Lead Nurturing Requires Too Much Staff Time","Texting prospects who haven't converted yet requires staff time. Automated nurture sequences keep warm leads engaged until they're ready to buy.","Users")],
  "Automated Text Messages That Run Your Business","AI-powered SMS that works while you work",
  "Infinite Rankers configures automated text message sequences tailored to your business lifecycle — appointment reminders, post-service review requests, lead follow-up sequences, and customer reactivation campaigns. All powered by AI personalization and triggered by your business events.",
  [cap("Appointment Reminder Sequences","Multi-touch reminders (72hr, 24hr, 2hr) that reduce no-shows by 40-60% automatically.","Calendar"),
   cap("Post-Service Review Requests","Review requests triggered by service completion — personalized with service details for maximum response.","Star"),
   cap("Lead Follow-Up Sequences","Multi-touch SMS follow-up for unconverted leads — keeping warm prospects engaged until they book.","TrendingUp"),
   cap("Customer Reactivation","Automated campaigns reaching lapsed customers with personalized reactivation offers.","RefreshCw")],
  [st("1","Trigger Event Occurs","A business event happens — appointment booked, service completed, lead form submitted — triggering the relevant automated sequence.","CheckCircle"),
   st("2","Personalized Text Sent","AI generates a personalized text based on the customer's specific situation — service type, history, and preferences.","MessageSquare"),
   st("3","Response Handled by AI","If the customer replies, AI manages the conversation — answering questions, rescheduling, or advancing toward booking.","Cpu"),
   st("4","Sequence Completes","The sequence runs to completion — whether that's a booked appointment, a posted review, or a customer marked for future reactivation.","CheckCircle")],
  "Automated SMS Results Across Business Scenarios",
  [cs("Elite Plumbing & Drain","Plumbing",[m("67%","No-Show Rate Reduction"),m("312%","More Reviews"),m("$22K","Monthly Revenue Growth")],"The appointment reminder sequence alone justified the entire platform. Our no-show rate dropped from 18% to 5% in 30 days. Then the review requests started generating 35+ reviews per month automatically. Two sequences transformed our business."),
   cs("Perfect Vision Optometry","Optometry",[m("89%","Appointment Show Rate"),m("267%","More Reviews"),m("45%","More Recall Visits")],"Automated recall reminders tell patients their annual eye exam is due. AI sends personalized texts referencing their last visit. Recall compliance went from 45% to 78% — that's massive revenue from an automated sequence."),
   cs("Alpine Tree Service","Tree Service",[m("178%","More Estimate Conversions"),m("4.8★","Google Rating"),m("$31K","Monthly Revenue")],"Lead follow-up sequences text prospects who requested estimates but didn't book. 3 messages over 7 days. Our estimate-to-booking conversion went from 35% to 61%. The AI follow-up closes more jobs than our sales team did manually.")],
  [fi("Appointment Reminder Sequences","72hr, 24hr, and 2hr reminders that dramatically reduce costly no-shows.","Calendar"),
   fi("Post-Service Review Requests","Completion-triggered review requests personalized with service details.","Star"),
   fi("Lead Nurture Sequences","Multi-touch follow-up converting uncommitted prospects into booked appointments.","TrendingUp"),
   fi("Customer Reactivation","Automated campaigns reactivating lapsed customers with personalized outreach.","RefreshCw"),
   fi("AI Response Handling","When customers reply to automated texts, AI manages the conversation intelligently.","Cpu"),
   fi("Sequence Performance Tracking","Real-time tracking of open rates, response rates, and conversions for every sequence.","BarChart3")],
  "Automated text messages are the highest-ROI set-and-forget marketing investment available to service businesses. Configure the sequences once — appointment reminders, review requests, lead nurture, reactivation — and they run indefinitely, generating consistent revenue from your existing customer base.",
  [{title:"Full Automation Stack",description:"Automated SMS is one layer of a complete AI Revenue System — combined with lead capture, booking, and CRM."},{title:"Sequence Analytics",description:"Every sequence tracked for performance — open rates, response rates, conversions, and revenue generated."},{title:"No Contract",description:"Month-to-month billing with full sequence library available from day one."}],
  [{title:"Local SEO",description:"Organic traffic feeds into SMS opt-in flows for continuous list growth."},{title:"Paid Advertising",description:"Campaign traffic funneled into SMS sequences for maximum lead nurturing."},{title:"Email Marketing",description:"SMS + email multi-channel sequences for maximum engagement across all customer preferences."}],
  [tm("Linda Ross","Owner","Ross Remodeling","The no-show reducer alone was worth it. We lost $400-600/week to no-shows. Automated 24hr and 2hr reminder texts dropped that to almost zero. Then we added review requests and reactivation. The whole system pays for itself many times over."),
   tm("Dr. Kevin Park","Chiropractor","Park Spine & Wellness","Recall reminder sequences bring patients back before they go elsewhere. AI texts patients who haven't been in 60+ days with personalized messages referencing their condition. Recall revenue increased 65% from automated texts."),
   tm("Samantha Hill","GM","Hill Pest Control","Lead follow-up texts work when phone calls get ignored. AI follows up with unconverted quote requests via 3 texts over 7 days. We close 30% of previously cold estimates through automated follow-up alone.")],
  [fq("What types of automated text sequences work best for my business?","The most impactful sequences vary by industry: Appointment businesses need reminders most urgently. Service businesses need post-service review requests. Sales-heavy businesses need lead follow-up sequences. Membership businesses need reactivation campaigns. We audit your situation and recommend the highest-ROI sequences first."),
   fq("Can I customize the automated message content?","Yes. All message templates are customized for your business, service types, and brand voice. You approve all templates before launch. AI adds personalization (customer name, service type, date) dynamically."),
   fq("How long until automated sequences start generating results?","Appointment reminder sequences show impact immediately — typically reducing no-shows within the first week. Review request sequences generate first automated reviews within 24 hours. Lead nurture sequences show conversion improvements within 30 days."),
   fq("Does the system stop texting if a customer responds?","Yes. When a customer responds to an automated sequence, AI handles the reply conversationally. Automated follow-up steps pause while the AI conversation is active — preventing conflicting messages."),
   fq("Can I run multiple automated sequences simultaneously?","Yes. Different sequences run for different customer segments simultaneously — new leads, recent customers, lapsed customers, and appointment-scheduled customers all receive appropriate, non-conflicting automated sequences.")],
  "Build Your Automated Text Message System Today","Free 30-minute demo — we'll identify your highest-ROI automated SMS sequences and show you exactly what each would generate for your business in the first 90 days.","Book My Free SMS Automation Demo",
  ["business-texting-software","sms-customer-follow-up","review-request-software","missed-call-text-back"]),

p("sms-marketing-platform","service",
  "SMS Marketing Platform | AI-Powered Business SMS | Infinite Rankers",
  "AI-powered SMS marketing platform for local businesses — manage campaigns, automate responses, and book appointments via text. 98% open rates guaranteed. Free demo.",
  "sms marketing platform, sms marketing software, text marketing platform, sms marketing tool",
  "98% Open Rate SMS Platform","SMS Marketing Platform","for Local Business Revenue",
  "A complete SMS marketing platform that goes beyond blasts — AI-powered two-way conversations, automated sequences, campaign management, and revenue tracking all in one system.",
  [m("98%","Guaranteed Open Rate"),m("45%","Avg. Response Rate"),m("3x","More Revenue vs Email"),m("No","Annual Contract")],
  "What a Real SMS Marketing Platform Delivers","Beyond basic bulk texting",
  [pt("Campaign Management at Scale","Professional SMS platforms manage contact lists, campaign scheduling, A/B testing, and performance reporting across all your SMS marketing activities.","BarChart3"),
   pt("Two-Way Conversation Handling","Mass blasting is one tool. A real platform also handles inbound replies intelligently — qualifying leads and booking appointments through AI-managed conversations.","MessageSquare"),
   pt("Audience Segmentation","Sending the same message to every contact wastes SMS budget and increases opt-outs. Platform-level segmentation ensures relevant messages reach the right customers.","Users"),
   pt("Revenue Attribution","Knowing which campaign sent what message is step one. A real platform shows which campaigns drove appointments, sales, and revenue — not just open rates.","DollarSign")],
  "Complete SMS Marketing Platform Features","Everything local businesses need in one platform",
  "Infinite Rankers' SMS marketing platform combines campaign management, audience segmentation, AI conversation handling, automated sequences, and revenue attribution — giving local businesses the same SMS marketing capabilities as enterprise brands.",
  [cap("Campaign Builder & Scheduler","Build and schedule promotional, reactivation, and seasonal campaigns with audience segmentation and send-time optimization.","FileText"),
   cap("AI Two-Way Reply Management","When customers reply to campaigns, AI handles conversations — qualifying leads and booking appointments automatically.","Cpu"),
   cap("Automated Sequence Library","Pre-built sequence templates for appointment reminders, review requests, lead nurture, and reactivation — customized for your business.","Layers"),
   cap("Revenue Dashboard","Track campaign revenue, cost per appointment, and total SMS marketing ROI in real-time.","DollarSign")],
  [st("1","Campaign Strategy",description:"We build your SMS marketing strategy — identifying audience segments, campaign types, and automated sequences for maximum revenue impact.",icon:"Target"),
   st("2","Platform Setup",description:"Contact list migration, audience segmentation, and all campaign templates configured — ready to launch within 5 business days.",icon:"Settings"),
   st("3","Campaign Launch",description:"First campaigns go live — promotional, reactivation, or automated sequences — and performance tracking begins immediately.",icon:"Rocket"),
   st("4","Revenue Reporting",description:"Monthly reports showing campaigns run, response rates, appointments booked, and revenue attributed to SMS marketing.",icon:"BarChart3")],
  "SMS Marketing Platform Results",
  [cs("Prestige Auto Detail","Auto Services",[m("$8,400","Revenue From SMS Campaigns"),m("267%","More Bookings"),m("4.8★","Customer Rating")],"Our quarterly SMS campaigns generate $8,400+ in detailing bookings consistently. The AI handles every reply — questions about packages, availability, pricing. We just review the calendar and show up to work."),
   cs("Valley Urgent Care","Healthcare",[m("189%","More Patient Visits"),m("91%","Show Rate"),m("4.9★","Patient Rating")],"Our SMS platform handles appointment reminders, post-visit surveys, and health tips for established patients. Patient satisfaction is up and no-shows are down 60%. SMS is our most effective patient communication channel."),
   cs("Peak Performance Gym","Fitness",[m("312%","More Membership Renewals"),m("44%","Lower Churn Rate"),m("$12K","Monthly Revenue Increase")],"Renewal reminder sequences prevent membership churn more effectively than any other channel. AI texts members 30 days before expiration with personalized renewal offers. Churn dropped from 12% to 4%.")],
  [fi("Campaign Builder","Professional campaign creation with audience targeting, scheduling, and personalization.","FileText"),
   fi("AI Reply Management","Two-way AI for handling campaign replies, qualifying leads, and booking appointments.","Cpu"),
   fi("Automated Sequences","Set-and-forget SMS sequences for every customer lifecycle stage.","Layers"),
   fi("Audience Segmentation","Targeted messaging by customer segment, service history, and behavior.","Users"),
   fi("Revenue Attribution","Track SMS marketing ROI from campaign message to booked appointment to revenue.","DollarSign"),
   fi("Compliance Management","TCPA consent tracking, opt-out management, and compliant messaging built in.","Shield")],
  "A complete SMS marketing platform is the infrastructure behind some of the most effective local business marketing. Combining campaign management, automated sequences, and AI reply handling creates a marketing engine that works continuously — generating bookings, reviews, and renewals without ongoing manual effort.",
  [{title:"Platform + Strategy",description:"We provide both the SMS platform and the marketing strategy — not just software you figure out yourself."},{title:"Done-For-You Campaigns",description:"Campaigns built and managed by our team — you focus on the business, we focus on the marketing."},{title:"Month-to-Month",description:"No annual commitment. Cancel anytime. We earn your renewal through results."}],
  [{title:"Local SEO",description:"SMS opt-in campaigns combined with local SEO create a complete organic acquisition engine."},{title:"Google Ads",description:"Paid traffic funneled into SMS opt-in flows for immediate engagement and long-term nurture."},{title:"Email Marketing",description:"Multi-channel SMS + email campaigns for maximum customer reach."}],
  [tm("Derek Evans","Owner","Evans Electric","Our SMS marketing platform manages 3 types of campaigns simultaneously — new customer acquisition, existing customer reactivation, and job completion reviews. The AI handles everything after we approve the initial templates. It's like having a marketing team at a fraction of the cost."),
   tm("Monica Liu","Owner","Liu Spa & Wellness","Monthly promotional SMS campaigns reliably generate 40-50 new appointments. At 3 cents per text, my marketing ROI on SMS is 50x minimum. No other channel comes close."),
   tm("Greg Nash","GM","Nash Roofing","Storm season SMS campaigns to our local area generate estimate requests we couldn't capture any other way. SMS is direct, immediate, and AI handles every reply. Our storm season revenue increased 67% since launching the platform.")],
  [fq("What's included in the SMS marketing platform?","Our platform includes campaign builder, audience segmentation, automated sequence library, AI two-way reply management, review request campaigns, revenue attribution dashboard, compliance management, and a dedicated marketing strategist — all in one package."),
   fq("How is this different from a basic SMS tool like SlickText or SimpleTexting?","Basic SMS tools manage delivery and contacts. Infinite Rankers' platform adds AI two-way conversation management, business system integration for automated triggers, revenue attribution, and full marketing strategy support — transforming SMS from a channel into a revenue system."),
   fq("Can I migrate my existing contact list?","Yes. We handle full contact list migration from any existing SMS platform — including all opt-in records, contact details, and history. No list rebuilding required."),
   fq("How many contacts and messages are included?","Platform packages are sized based on your contact list and monthly message volume. We don't apply artificial caps — pricing is transparent and based on actual usage."),
   fq("What's the setup and onboarding timeline?","Most clients are fully operational within 5-7 business days — including contact migration, segment configuration, campaign template build, and AI conversation setup.")],
  "Get the SMS Marketing Platform That Drives Real Revenue","Free 30-minute platform demo — see your SMS marketing strategy, first campaign plan, and projected revenue impact before committing to anything.","Book My Free SMS Platform Demo",
  ["business-texting-software","text-message-marketing-for-small-business","automated-text-messages-for-business","sms-customer-follow-up"]),

p("automated-customer-texting","service",
  "Automated Customer Texting | AI SMS for Business Follow-Up | Infinite Rankers",
  "Automated customer texting that follows up with every lead, reminds every appointment, and requests every review — automatically. Zero manual effort. Free demo.",
  "automated customer texting, automated customer sms, customer text automation, automatic text messaging customers",
  "Zero Manual Texting Required","Automated Customer Texting","That Does the Work for You",
  "Forget manually texting customers for follow-up, reminders, and review requests. Our AI-powered automated customer texting system handles every message at the perfect time — so your team focuses on serving customers, not texting them.",
  [m("100%","Customer Coverage"),m("98%","SMS Open Rate"),m("Zero","Manual Texting"),m("7 days","To Full Automation")],
  "The Hidden Cost of Manual Customer Texting","What your team is doing instead of serving customers",
  [pt("Hours Per Week Wasted on Texts","Most businesses have staff spending 2-4 hours per week manually texting customers for follow-up, reminders, and review requests. AI automation eliminates this entirely.","Clock"),
   pt("Inconsistency Loses Revenue","Manual texting means some customers get followed up, others don't. Some get reminders, others miss them and no-show. Inconsistency costs thousands in missed opportunities.","AlertTriangle"),
   pt("After-Hours Inquiries Get Ignored","New customer inquiries that come in after 5pm get no response until the next morning. By then, 78% have already called a competitor who answered. AI responds in 30 seconds.","Moon"),
   pt("Review Requests Timed Wrong","The best time to request a review is immediately after service. Manual review texting is almost always late — costing you responses from customers at peak satisfaction.","Star")],
  "Automated Customer Texting That Covers Every Scenario","Complete SMS automation for every stage of the customer relationship",
  "Infinite Rankers' automated customer texting system handles every customer text scenario — new lead response, appointment confirmation, appointment reminder, post-service follow-up, review requests, and reactivation campaigns — with AI that personalizes every message and handles every reply.",
  [cap("Instant Lead Response","New customer inquiries answered via text within 30 seconds — 24/7, including nights and weekends.","Zap"),
   cap("Appointment Reminder Automation","Multi-touch reminders that dramatically reduce costly no-shows without any manual scheduling.","Calendar"),
   cap("Post-Service Follow-Up","Automated post-service check-in and review requests timed to peak satisfaction moments.","Star"),
   cap("Reactivation Campaigns","Automated campaigns reaching lapsed customers with personalized messages that bring them back.","RefreshCw")],
  [st("1","New Lead Arrives","New inquiry comes in via any channel — AI texts back within 30 seconds to begin qualification.","Zap"),
   st("2","Appointment Confirmed","Appointment booked — automated confirmation and multi-touch reminders launch immediately.","Calendar"),
   st("3","Service Completed","Service marked complete — post-service check-in and review request fire automatically at the right moment.","Star"),
   st("4","Lapsed Customer",description:"Customer hasn't returned in 60+ days — automated reactivation campaign launches with personalized messaging.",icon:"RefreshCw")],
  "Automated Customer Texting Results",
  [cs("Bright & Clean Maids","Home Cleaning",[m("100%","Customer Text Coverage"),m("267%","More Reviews"),m("78%","No-Show Reduction")],"We text every single customer at every stage — confirmation, reminder, post-service, review request. All automated. Our no-show rate dropped 78%, reviews tripled, and our team focuses entirely on cleaning, not texting."),
   cs("Prime Auto Collision","Auto Body",[m("312%","More Review Volume"),m("4.9★","Google Rating"),m("44%","More Referrals")],"Automated post-service texts at completion — 'How's the car looking?' plus review request — generate 35+ reviews per month. Customer satisfaction scores went up because we're consistently following up. People love to feel remembered."),
   cs("Signature Salon","Personal Services",[m("89%","Appointment Show Rate"),m("178%","More Bookings"),m("4.8★","Client Rating")],"Before automation, our front desk manually texted appointment reminders. That's 30 minutes a day that now goes to client service. Show rate went from 71% to 89% because reminders are perfectly timed automatically.")],
  [fi("Instant Lead Response","30-second automated reply to every new customer inquiry — 24/7 coverage including nights and weekends.","Zap"),
   fi("Appointment Confirmation","Instant booking confirmation via text with all relevant details automatically included.","CheckCircle"),
   fi("Multi-Touch Reminders","72hr, 24hr, and 2hr appointment reminders reducing no-shows by 40-70%.","Calendar"),
   fi("Post-Service Check-In","Automated check-in text after service completion — catching any issues before they become reviews.","MessageSquare"),
   fi("Review Request Automation","Personalized review requests timed to peak satisfaction for maximum response rates.","Star"),
   fi("Lapsed Customer Reactivation","Automated campaigns bringing back customers who haven't returned in 60+ days.","RefreshCw")],
  "Automated customer texting creates consistency that manual texting can never achieve — every customer, every time, perfectly timed. This consistency compounds over months: more reviews from consistent post-service requests, fewer no-shows from consistent reminders, more referrals from consistent follow-up.",
  [{title:"Complete Coverage",description:"Every customer lifecycle stage covered — lead, appointment, post-service, review, and reactivation."},{title:"AI Personalization",description:"Every automated text personalized with customer name, service type, and relevant details — never feeling generic."},{title:"No Contract",description:"Month-to-month automated texting. No annual commitments. Cancel anytime with 30 days notice."}],
  [{title:"Local SEO",description:"Reviews generated by automated post-service texts fuel local search ranking improvement."},{title:"CRM Integration",description:"Every automated text sequence triggers and updates your CRM for complete customer record management."},{title:"Email Automation",description:"Combined SMS + email automation for maximum coverage across all customer communication preferences."}],
  [tm("Patricia Moore","Owner","Moore's Deep Clean","Automated customer texting handles the relationship management that used to take an hour a day. Every customer gets confirmation, reminders, and follow-up. Our satisfaction scores are at all-time highs and we've never been more consistent."),
   tm("Tony Ricci","Owner","Ricci's Auto Repair","We text every customer automatically at 5 stages. The only manual effort is when AI escalates a complex question to us. Everything else — reminder, review request, follow-up — happens automatically. Game changer for a 4-person shop."),
   tm("Dr. Jamie Wells","Dentist","Wells Dental","Automated dental follow-up texts post-procedure are particularly effective. 'How's the feeling after your filling?' AI checks in, handles concerns, and requests a review if everything went well. Patient retention went up 40%.")]  ,
  [fq("How is automated customer texting different from manual texting?","The difference is consistency, timing, and scale. Automated texting covers 100% of customers, at exactly the right moment, every single time — without anyone remembering to send it. Manual texting covers whoever staff remember, when they have time, with inconsistent timing."),
   fq("Can I see all automated texts before they go out?","Yes. All templates are approved by you before launch. You can also review sent messages and conversation logs from the dashboard at any time."),
   fq("What happens when a customer replies to an automated text?","AI handles the reply conversationally. It answers questions, addresses concerns, and advances toward the next stage (booking, review, etc.). Complex conversations are flagged for human review when outside the AI's configured scope."),
   fq("How do I set up automated customer texting?","We handle all setup — system integration, template building, sequence configuration, and test runs. You participate in a 45-minute onboarding session to approve templates and review the sequences before launch. Total elapsed time is typically 5-7 business days."),
   fq("Does the automation handle customers who opt out?","Yes. Opt-out requests are processed immediately and that customer is removed from all future automated sequences. Opt-out tracking is maintained in compliance with TCPA regulations.")],
  "Automate Every Customer Text — Free Setup Consultation","Free 30-minute consultation — we'll map every customer text your business currently sends manually and show you exactly how to automate all of it within 7 days.","Book My Free Automation Consultation",
  ["business-texting-software","sms-marketing-platform","review-request-software","text-message-marketing-for-small-business"]),

p("sms-customer-follow-up","service",
  "SMS Customer Follow-Up | AI Automated Text Follow-Up System | Infinite Rankers",
  "SMS customer follow-up that never misses a lead — AI sends personalized follow-up texts after estimates, appointments, and services automatically. 3x more conversions. Free demo.",
  "sms customer follow-up, text follow up customers, sms follow up system, automated text follow up, customer follow up text",
  "3x More Conversions From Follow-Up","SMS Customer Follow-Up","That Converts 3x More Leads",
  "Most businesses follow up with 1 in 3 prospects by text. Our AI follows up with every single prospect — at the right time, with the right message — converting 3x more leads than manual follow-up.",
  [m("3x","More Lead Conversions"),m("100%","Follow-Up Coverage"),m("5-touch","Automated Sequence"),m("Zero","Manual Follow-Up")],
  "The Follow-Up Gap That Kills Revenue","Why most businesses lose 60% of closable leads",
  [pt("80% of Sales Require 5+ Follow-Ups","Studies consistently show 80% of sales happen after the 5th contact. But 44% of salespeople stop after 1 attempt. Automated SMS follow-up sequences close the gap.","TrendingDown"),
   pt("Phone Follow-Up Gets Ignored","78% of calls from unknown numbers go to voicemail. Texts get read — and replied to — at 6x the rate of calls for follow-up communication.","Phone"),
   pt("Email Follow-Up Has Low Engagement","Follow-up emails average 15-25% open rates. SMS follow-up averages 98% open rates and 45% reply rates. The channel difference alone 3x's your follow-up effectiveness.","Mail"),
   pt("Manual Follow-Up Is Inconsistent","Human follow-up depends on who remembers, how busy they are, and whether the lead fell through the cracks. Automation ensures 100% coverage, every time.","AlertTriangle")],
  "AI SMS Follow-Up That Closes More Business","Automated, personalized, persistent — without being annoying",
  "Our AI SMS follow-up system sends personalized follow-up texts to every prospect at the optimal intervals — after estimates, after consultations, after service, and to reactivate lapsed customers — with intelligent sequences that stop when the prospect converts.",
  [cap("Post-Estimate Follow-Up","Multi-touch follow-up sequences for prospects who requested estimates but haven't booked — converting fence-sitters into jobs.",icon:"FileText"),
   cap("Consultation Follow-Up","Follow-up sequences after sales calls or consultations — addressing objections via text and advancing toward commitment.",icon:"MessageSquare"),
   cap("Lapsed Lead Reactivation","Automated campaigns reaching warm leads who expressed interest but went cold — with personalized follow-up that feels timely.",icon:"RefreshCw"),
   cap("Smart Sequence Stopping","Sequences stop automatically when a prospect books, buys, or explicitly opts out — no annoying follow-up after conversion.",icon:"CheckCircle")],
  [st("1","Estimate or Consultation Completed","A prospect receives an estimate or has a consultation — triggering a multi-touch follow-up sequence automatically.",icon:"FileText"),
   st("2","Personalized SMS at Day 1","AI sends a personalized follow-up text the next day — referencing the specific estimate or consultation with a clear next-step ask.",icon:"MessageSquare"),
   st("3","Follow-Up at Days 3 and 7","Two additional touchpoints at optimal intervals — each with slightly different messaging and value reinforcement.",icon:"TrendingUp"),
   st("4","Final Reactivation at Day 14","Final attempt with a value-add or limited-time offer — then the lead moves to periodic reactivation if still unconverted.",icon:"RefreshCw")],
  "SMS Follow-Up Conversion Results",
  [cs("Premier Roofing & Gutters","Roofing",[m("58%","Estimate-to-Booking Rate"),m("3x","More Conversions"),m("$67K","Revenue Recovered")],"Our estimate follow-up sequence closes jobs that used to fall through. We went from 28% to 58% estimate-to-booking rate just from 3 personalized SMS follow-ups. That's $67K in annual revenue we were leaving on the table."),
   cs("Advanced Dental Care","Dental",[m("67%","Consultation Conversion"),m("189%","More New Patients"),m:"$31K","Monthly Revenue Growth")],"Consultation follow-up sequences convert more potential patients into first appointments. AI follows up at 1, 3, and 7 days post-consultation with value-adds and easy booking links. Conversion went from 38% to 67%."),
   cs("Mountain States Plumbing","Plumbing",[m("3.1x","More Closings From Quotes"),m("$43K","Quarterly Revenue"),m("89%","Customer Satisfaction")],"We quote 200+ jobs per month and used to book 28% of them. SMS follow-up sequences brought that to 62% — still serving the same number of quotes but closing more than twice as many.")],
  [fi("Post-Estimate Follow-Up","Multi-touch SMS sequence converting estimate requests into booked jobs.",icon:"FileText"),
   fi("Consultation Follow-Up","Automated follow-up after sales calls converting more prospects to customers.",icon:"MessageSquare"),
   fi("Objection Handling via Text","AI addresses common objections (price, timing, comparison shopping) through personalized follow-up texts.",icon:"Shield"),
   fi("Lapsed Lead Reactivation","Re-engage cold prospects with personalized reactivation campaigns that feel timely.",icon:"RefreshCw"),
   fi("Booking Link in Every Text","Every follow-up text includes a direct booking link — one tap to convert.",icon:"Link"),
   fi("Conversion Tracking","Track every lead from first contact through booking — seeing exactly which follow-up touches drove conversion.",icon:"BarChart3")],
  "SMS customer follow-up is the highest-ROI activity for service businesses with significant estimate or consultation volume. Converting even 10% more estimates via automated follow-up generates significant monthly revenue — often 5-10x the cost of the entire follow-up system.",
  [{title:"Follow-Up + Full Funnel",description:"SMS follow-up is one component of a complete AI Revenue System from lead capture to closed customer."},{title:"CRM Integration",description:"Every follow-up sequence updates your CRM — moving deal stages and triggering next-step automations."},{title:"No Contract",description:"Month-to-month follow-up automation with full sequence library available from day one."}],
  [{title:"Lead Generation",description:"More leads to follow up with — organic SEO and paid ads feeding continuous lead volume."},{title:"Landing Page Optimization",description:"Higher-converting landing pages reduce the follow-up load by converting more leads on first contact."},{title:"Email Follow-Up",description:"Multi-channel SMS + email follow-up for maximum coverage and conversion rates."}],
  [tm("Carlos Rivera","Owner","Rivera Landscaping","We quote 300+ jobs per year. Before follow-up automation, we booked maybe 30%. Now we book 58%. That's 84 additional jobs per year from the same quote volume. The follow-up system paid for itself in week two."),
   tm("Dr. Sarah Lee","Practice Owner","Lee Chiropractic","New patient consultation follow-up sequences convert fence-sitters who need one more nudge. AI sends 3 texts over 7 days. Our consultation-to-patient conversion went from 40% to 67%. 40% more patients from the same consultation volume."),
   tm("Bill Thompson","Owner","Thompson Windows & Doors","I used to lose 70% of my quotes because I forgot to follow up. Now 100% of quotes get 3 automated SMS follow-ups. I'm closing jobs I would have lost completely. It's the simplest revenue unlock I've ever done.")],
  [fq("How many follow-up texts are in a typical sequence?","We configure sequences based on your industry and sales cycle. Most sequences include 3-5 texts over 7-14 days — enough to reach the majority of convertible prospects without being excessive. All sequences stop immediately when a prospect books or opts out."),
   fq("What tone should follow-up texts use?","We build follow-up sequences in your brand voice — professional but warm, persistent but not pushy. AI adds personalization referencing the specific estimate or conversation to make each follow-up feel relevant, not automated."),
   fq("Can the AI handle price objections via text?","Yes. We configure AI responses to common objections — price concerns, timing delays, comparison shopping. The AI addresses these naturally via text, often rescuing leads that would have gone to competitors."),
   fq("How do I know which follow-up texts are working?","Our conversion dashboard shows response rates, booking rates, and revenue generated for each follow-up touch in the sequence — letting us continuously optimize messaging and timing for maximum conversion."),
   fq("What's the minimum lead volume for SMS follow-up to be worth it?","Even at 20 estimates per month, SMS follow-up automation typically pays for itself within 30 days. At 50+ estimates per month, the ROI compounds significantly. We provide a detailed ROI projection based on your specific lead volume before you commit.")],
  "Stop Losing Closable Leads to Slow Follow-Up","Free 30-minute consultation — we'll calculate the revenue you're losing from unconverted estimates and show you exactly how SMS follow-up automation would recover it.","Book My Free Follow-Up Audit",
  ["automated-text-messages-for-business","business-texting-software","two-way-text-messaging-for-business","improve-lead-response-time"])
];

// Fix the nested object issue
pages.forEach(p => {
  if (p.pipeline && p.pipeline.steps) {
    p.pipeline.steps.forEach(s => {
      if (s.description === undefined && s.desc !== undefined) {
        s.description = s.desc; delete s.desc;
      }
    });
  }
});

addPages(pages);
console.log("Batch 4 complete: SMS/texting pages added");
